services:
  - type: web
    name: crsis-link-api
    env: docker
    dockerfilePath: ./crsis_link_server/Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: runmode
        value: production
      - key: PORT
        value: 8080
      - key: PUBLIC_HOST
        value: crsis-link-api.onrender.com
      - key: SERVERPOD_PASSWORDS
        sync: false
      - key: SERVERPOD_PASSWORD_redis
        value: 'none'
      - key: SERVERPOD_DATABASE_HOST
        fromDatabase:
          name: crsis-link-db
          property: host
      - key: SERVERPOD_DATABASE_PORT
        fromDatabase:
          name: crsis-link-db
          property: port
      - key: SERVERPOD_DATABASE_NAME
        fromDatabase:
          name: crsis-link-db
          property: database
      - key: SERVERPOD_DATABASE_USER
        fromDatabase:
          name: crsis-link-db
          property: user
      - key: SERVERPOD_PASSWORD_database
        fromDatabase:
          name: crsis-link-db
          property: password
      - key: SERVERPOD_REDIS_HOST
        fromService:
          type: redis
          name: crsis-link-redis
          property: host
      - key: SERVERPOD_REDIS_PORT
        fromService:
          type: redis
          name: crsis-link-redis
          property: port

  - type: redis
    name: crsis-link-redis
    plan: free
    region: oregon
    ipAllowList: []

databases:
  - name: crsis-link-db
    databaseName: serverpod
    plan: free
    region: oregon
